### ISSUE TITLE
Skeleton's `.clear` makes WordPress footers, well, disappear!

### ISSUE THREAD

**Issue by nfreear** [mhawksey/wp-evidence-hub#20]
As used in some evidence hub shortcodes, eg. `[evidence_map]`:
- http://evidence.laceproject.eu/?page_id=159

CSS - a different interpretation of `.clear` in Skeleton, compared with WordPress/ Tiny-Forge theme! 
- https://github.com/mhawksey/wp-evidence-hub/blob/master/lib/map/css/skeleton.css#L235
- https://github.com/dhg/Skeleton/blob/master/stylesheets/skeleton.css#L235

``` css
    /* You can also use a <br class="clear" /> to clear columns */
    .clear {
      clear: both;
      display: block;
      overflow: hidden;
      visibility: hidden;
      width: 0;
      height: 0;
    }
```
